import type { Order, RecentFile, IndexRow } from "@/app/components/feature/tables/types";

export const ORDERS: Order[] = [
  {
    no: "26050012",
    apn: "123-456-78",
    addr: "123 Main St",
    owner: "Michael Smith",
    county: "Los Angeles",
    fileNo: "ESC-2026-4412",
    productType: "CLTA Owner",
    status: "Open",
  },
  {
    no: "26050018",
    apn: "458-888-12",
    addr: "458 Oak Ave",
    owner: "John Doe",
    county: "Riverside",
    fileNo: "ESC-2026-3391",
    productType: "ALTA Lender",
    status: "Closed",
  },
  {
    no: "26050019",
    apn: "789-444-98",
    addr: "88 Sunset Blvd",
    owner: "James Parker",
    county: "San Diego",
    fileNo: "ESC-2026-2204",
    productType: "CLTA Owner",
    status: "Cancelled",
  },
  {
    no: "26050023",
    apn: "321-111-55",
    addr: "44 Palm Drive",
    owner: "Sara Lee",
    county: "Orange",
    fileNo: "ESC-2026-5519",
    productType: "ALTA Homeowners",
    status: "Open",
  },
  {
    no: "26050027",
    apn: "654-222-33",
    addr: "99 Harbor Blvd",
    owner: "Tom Brown",
    county: "Ventura",
    fileNo: "ESC-2026-6630",
    productType: "CLTA/ALTA",
    status: "Open",
  },
  {
    no: "26050031",
    apn: "987-333-77",
    addr: "55 Willow Lane",
    owner: "Amy Chang",
    county: "San Bernardino",
    fileNo: "ESC-2026-7741",
    productType: "ALTA Lender",
    status: "Open",
  },
];

export const RECENT_FILES: RecentFile[] = [
  {
    no: "#26050012",
    addr: "123 Main Street, Los Angeles",
    owner: "Michael Smith",
    status: "Open",
  },
  {
    no: "#26050018",
    addr: "458 Oak Ave, Riverside",
    owner: "John Doe",
    status: "Closed",
  },
  {
    no: "#26050019",
    addr: "88 Sunset Blvd, San Diego",
    owner: "James Parker",
    status: "Cancelled",
  },
];

export const TC_ROWS: IndexRow[] = [
  {
    rec: "06/12/2019",
    abbr: "QCD",
    entity: "XFER",
    docTitle: "Quitclaim Deed",
    instr: "2019-0098234",
    book: "",
    pg: "",
    grantor: "ESTATE OF HELEN SMITH",
    grantee: "MICHAEL SMITH",
  },
  {
    rec: "05/17/2025",
    abbr: "GD",
    entity: "XFER",
    docTitle: "Grant Deed",
    instr: "2023-0212342",
    book: "",
    pg: "",
    grantor: "MICHAEL SMITH",
    grantee: "JOHN D DOE",
  },
  {
    rec: "03/22/2020",
    abbr: "DOT",
    entity: "DOT",
    docTitle: "Deed of Trust",
    instr: "2020-0044512",
    book: "",
    pg: "",
    grantor: "MICHAEL SMITH",
    grantee: "WELLS FARGO BANK",
  },
  {
    rec: "11/05/2022",
    abbr: "RECON",
    entity: "DOT",
    docTitle: "Reconveyance",
    instr: "2022-0189001",
    book: "",
    pg: "",
    grantor: "WELLS FARGO BANK",
    grantee: "MICHAEL SMITH",
    parentInstr: "2020-0044512",
  },
  {
    rec: "04/17/2023",
    abbr: "DOT",
    entity: "DOT",
    docTitle: "Deed of Trust",
    instr: "2025-0213146",
    book: "",
    pg: "",
    grantor: "JOHN D DOE",
    grantee: "BANK OF AMERICA",
  },
  {
    rec: "09/14/2021",
    abbr: "MECH",
    entity: "LIEN",
    docTitle: "Mechanic's Lien",
    instr: "2021-0077893",
    book: "",
    pg: "",
    grantor: "ACME CONTRACTORS",
    grantee: "MICHAEL SMITH",
  },
  {
    rec: "01/30/2024",
    abbr: "JUDG",
    entity: "LIEN",
    docTitle: "Judgment Lien",
    instr: "2024-0031122",
    book: "",
    pg: "",
    grantor: "COUNTY OF LOS ANGELES",
    grantee: "JOHN D DOE",
  },
  {
    rec: "08/03/2022",
    abbr: "NOC",
    entity: "MISC",
    docTitle: "Notice of Completion",
    instr: "2022-0143900",
    book: "",
    pg: "",
    grantor: "MICHAEL SMITH",
    grantee: "\u2014",
  },
  {
    rec: "04/11/1998",
    abbr: "EASE",
    entity: "EASE",
    docTitle: "Easement",
    instr: "1998-0022341",
    book: "",
    pg: "",
    grantor: "CITY OF GLENDALE",
    grantee: "PUBLIC",
  },
  {
    rec: "07/19/2005",
    abbr: "CCR",
    entity: "EASE",
    docTitle: "CC&Rs",
    instr: "2005-0188770",
    book: "",
    pg: "",
    grantor: "SUNSET HILLS HOA",
    grantee: "ALL OWNERS",
  },
];
