import type { PropertyForm, FormData } from "../../types";


export const STEPS = [
  { id: 0, label: "Dashboard", short: "Dashboard", icon: "dashboard" },
  { id: 1, label: "Title Chain Review", short: "Chain", icon: "link" },
  { id: 2, label: "TSRI", short: "TSRI", icon: "fileCheck" },
  { id: 3, label: "Documents & Notes", short: "Docs", icon: "clipboard" },
  { id: 4, label: "Final Review", short: "Review", icon: "shield" },
];

export const NAV_ICONS = [
  { name: "dashboard", label: "Dashboard", active: false },
  // { name: "orders", label: "Orders", active: false },
  // { name: "search", label: "Search", active: false },
  // { name: "link", label: "Title Chain", active: false },
  // { name: "file", label: "Documents", active: false },
  // { name: "tasks", label: "Tasks", active: true },
  // { name: "chart", label: "Reports", active: false },
  { name: "settings", label: "Admin", active: false },
];

export const IDX_COLS = [
  "",
  "Rec Date",
  "Abbr",
  "Grantor",
  "Grantee",
  "Instrument / Book-Page",
  "Entity / Doc Title",
  "Image",
  // "Add Code",
];

export const INDEX_SECTIONS = [
  { title: "Assessor Page", sub: "Assessor records and parcel data", accent: "#0369a1", rows: [] },
  { title: "Assessor Map", sub: "Parcel map and boundary information", accent: "#0891b2", rows: [] },
  { title: "Tract Map", sub: "Recorded tract map references", accent: "#0d9488", rows: [] },
  { title: "Tax Cert", sub: "Tax certificate and payment records", accent: "#65a30d", rows: [] },
  { title: "Runsheet", sub: "Search runsheet and index entries", accent: "#7c3aed", rows: [] },
  { title: "Other Exceptions", sub: "Additional title exceptions noted", accent: "#dc2626", rows: [] },
  { title: "Other Requirements", sub: "Additional requirements and conditions", accent: "#d97706", rows: [] },
  { title: "Starters", sub: "Starter documents and prior policy references", accent: "#475569", rows: [] },
  { title: "Title Chain Review", sub: "Full chain of title — deeds, liens, easements", accent: "#8B0000", rows: [] },
];

export const COUNTIES: string[] = [];

export const DOC_SEARCH_TYPES = [
  "Grant Deed",
  "Deed of Trust",
  "Quitclaim Deed",
  "Reconveyance",
  "Notice",
  "Easement",
  "CC&Rs",
  "Mechanic's Lien",
  "Judgment Lien",
  "Any Document",
];

export interface GenieCodeItem {
  code: string;
  label: string;
  body: string;
}

export const CAEXC_CODES: GenieCodeItem[] = [];

export const CAREQ_CODES: GenieCodeItem[] = [];

export const CREATE_STEPS: string[] = [];

export const EMPTY_FORM: PropertyForm = {
  addrNo: "",
  dirPrefix: "",
  streetName: "",
  suffix: "",
  postDir: "",
  unitType: "",
  unitNo: "",
  city: "",
  state: "",
  zip: "",
  county: "",
  apn1: "",
  apn2: "",
  apn3: "",
  apn4: "",
  lot: "",
  block: "",
  tract: "",
  mapBook: "",
  page: "",
  section: "",
  township: "",
  range: "",
  shortLegal: "",
  municipality: "",
  jurisdiction: "",
  vestingText: "",
  vestingType: "",
  landUse: "",
};

export const DEFAULT_FORM: FormData = {
  search: {
    type: "APN",
    apnInput: "",
    zipInput: "",
    addrNum: "",
    addrStr: "",
    addrCity: "",
    addrState: "",
    addrZip: "",
    ownerName: "",
    propId: "",
    fullAddr: "",
    advCounty: "",
    advYear: "",
    advBeds: "",
  },
  property: { ...EMPTY_FORM },
  file: {
    clientName: "",
    clientFileNo: "",
    transactionType: "",
    productType: "",
    sourceOfBusiness: "",
    loanNumber: "",
    editMode: false,
    editOrderNo: "",
    editOpenDate: "",
    editStatus: "",
    editRush: false,
    editClientFileNo: "",
    editSource: "",
    editCloseDate: "",
    editDelivery: "",
    editSegment: "",
    editTransType: "",
    editProductType: "",
    editUnderwriter: "",
    editSalePrice: "",
    editLoanAmt: "",
    editLoanNo: "",
    editInsuredAmt: "",
    editPremOwners: "",
    editPremLenders: "",
    editPremBinder: "",
    editOwnersPolicy: "",
    editLoanPolicy: "",
    editBinderPolicy: "",
    editEscrowRef: "",
    editTitleOfficer: "",
    editTitleOfficerEmail: "",
    editEscrowOfficer: "",
    editEscrowOfficerEmail: "",
    editTitleRep: "",
    editTitleRepEmail: "",
    editTitleRepPct: "",
    editFileSource: "",
  },
  escrow: {
    escrowNo: "",
    escrowCompany: "",
    titleOffice: "",
    escrowOffice: "",
    branch: "",
    loanOfficer: "",
    lender: "",
  },
  parties: {
    buyers: [],
    sellers: [],
    bFirst: "",
    bLast: "",
    bMid: "",
    bVest: "",
    bPhone: "",
    bEmail: "",
    bAddr: "",
    bCity: "",
    bState: "",
    bZip: "",
    bEntity: "",
    bSSN: "",
    sFirst: "",
    sLast: "",
    sMid: "",
    sVest: "",
    sPhone: "",
    sEmail: "",
    sAddr: "",
    sDeedType: "",
    sDocNo: "",
    titleOffice: "",
    escrowOffice: "",
    branch: "",
    titleOfficer: "",
    titleOfficerEmail: "",
    escrowOfficer: "",
    escrowOfficerEmail: "",
    loanOfficer: "",
    lender: "",
    laCompany: "",
    laCompDre: "",
    laContact: "",
    laContDre: "",
    laAddr: "",
    laCity: "",
    laState: "",
    laZip: "",
    laPhone: "",
    laFax: "",
    laMobile: "",
    laEmail: "",
    laRef: "",
    saCompany: "",
    saCompDre: "",
    saContact: "",
    saContDre: "",
    saAddr: "",
    saCity: "",
    saState: "",
    saZip: "",
    saPhone: "",
    saFax: "",
    saMobile: "",
    saEmail: "",
    saRef: "",
    lsaCompany: "",
    lsaCompDre: "",
    lsaContact: "",
    lsaContDre: "",
    lsaAddr: "",
    lsaCity: "",
    lsaState: "",
    lsaZip: "",
    lsaPhone: "",
    lsaFax: "",
    lsaMobile: "",
    lsaEmail: "",
    lsaRef: "",
    ldCompany: "",
    ldCompNmls: "",
    ldContact: "",
    ldContNmls: "",
    ldAddr: "",
    ldCity: "",
    ldState: "",
    ldZip: "",
    ldPhone: "",
    ldFax: "",
    ldMobile: "",
    ldEmail: "",
    ldRef: "",
    mbCompany: "",
    mbCompNmls: "",
    mbContact: "",
    mbContNmls: "",
    mbAddr: "",
    mbCity: "",
    mbState: "",
    mbZip: "",
    mbPhone: "",
    mbFax: "",
    mbMobile: "",
    mbEmail: "",
    mbRef: "",
    pcCompany: "",
    pcCompId: "",
    pcContact: "",
    pcContId: "",
    pcAddr1: "",
    pcCity: "",
    pcState: "",
    pcZip: "",
    pcPhone: "",
    pcEmail: "",
    clCompany: "",
    clCompId: "",
    clContact: "",
    clContId: "",
    clAddr: "",
    clCity: "",
    clState: "",
    clZip: "",
    clPhone: "",
    clEmail: "",
  },
};
