import type { PropertyForm, FormData } from "@/app/components/feature/tables/types"
import type { CreateOrderRequest } from "./types"
import type { PartiesState } from "./steps/step-parties"

export function buildCreatePayload(
  property: PropertyForm,
  file: FormData["file"],
  escrow: FormData["escrow"],
  parties: PartiesState | null,
): CreateOrderRequest {
  return {
    orderNumber: file.editOrderNo || undefined,
    addrNo: property.addrNo ?? "",
    dirPrefix: property.dirPrefix ?? "",
    streetName: property.streetName ?? "",
    suffix: property.suffix ?? "",
    postDir: property.postDir ?? "",
    unitType: property.unitType ?? "",
    unitNo: property.unitNo ?? "",
    city: property.city ?? "",
    state: property.state ?? "",
    zipCode: property.zip ?? "",
    county: property.county ?? "",
    apn1: property.apn1 ?? "",
    apn2: property.apn2 ?? "",
    apn3: property.apn3 ?? "",
    apn4: property.apn4 ?? "",
    lot: property.lot ?? "",
    block: property.block ?? "",
    tract: property.tract ?? "",
    mapBook: property.mapBook ?? "",
    page: property.page ?? "",
    section: property.section ?? "",
    township: property.township ?? "",
    range: property.range ?? "",
    shortLegal: property.shortLegal ?? "",
    assessorVesting: property.vestingText ?? "",
    vestingType: property.vestingType ?? "",
    landUse: property.landUse ?? "",
    municipality: property.municipality ?? "",
    jurisdiction: property.jurisdiction ?? "",
    clientName: file.clientName ?? "",
    clientFileNo: file.clientFileNo ?? "",
    transactionType: file.transactionType ?? file.editTransType ?? "",
    productType: file.productType ?? file.editProductType ?? "",
    sourceOfBusiness: file.sourceOfBusiness ?? file.editSource ?? "",
    loanAmount: file.editLoanAmt ?? "",
    loanNumber: file.editLoanNo ?? file.loanNumber ?? "",
    estimatedClosingDate: file.editCloseDate ?? "",
    expectedDelivery: file.editDelivery ?? "",
    businessSegment: file.editSegment ?? "",
    underwriter: file.editUnderwriter ?? "",
    salePrice: file.editSalePrice ?? "",
    insuredAmount: file.editInsuredAmt ?? "",
    premiumOwners: file.editPremOwners ?? "",
    premiumLenders: file.editPremLenders ?? "",
    premiumBinder: file.editPremBinder ?? "",
    ownersPolicyNo: file.editOwnersPolicy ?? "",
    loanPolicyNo: file.editLoanPolicy ?? "",
    binderPolicyNo: file.editBinderPolicy ?? "",
    escrowCoRefNo: file.editEscrowRef ?? "",
    titleOfficer: file.editTitleOfficer ?? "",
    titleOfficerEmail: file.editTitleOfficerEmail ?? "",
    escrowOfficer: file.editEscrowOfficer ?? "",
    escrowOfficerEmail: file.editEscrowOfficerEmail ?? "",
    titleRep: file.editTitleRep ?? "",
    titleRepEmail: file.editTitleRepEmail ?? "",
    titleRepPercent: file.editTitleRepPct ?? "",
    fileSource: file.editFileSource ?? "",
    titleOffice: escrow.titleOffice ?? parties?.titleOffice ?? "",
    escrowOffice: escrow.escrowOffice ?? parties?.escrowOffice ?? "",
    titleBranchReview: escrow.branch ?? parties?.branch ?? "",
    loanOfficer: escrow.loanOfficer ?? parties?.loanOfficer ?? "",
    lenderBank: escrow.lender ?? parties?.lender ?? "",
    buyers: (parties?.buyers ?? []).map((b) => ({
      firstName: b.first ?? "",
      lastName: b.last ?? "",
      middleSuffix: b.mid ?? "",
      entityType: b.entity ?? "",
      vesting: b.vesting ?? "",
      phone: b.phone ?? "",
      email: b.email ?? "",
      mailingAddress: b.addr ?? "",
      city: b.city ?? "",
      state: b.state ?? "",
      zip: b.zip ?? "",
      ssnTaxId: b.ssn ?? "",
    })),
    sellers: (parties?.sellers ?? []).map((s) => ({
      firstName: s.first ?? "",
      lastName: s.last ?? "",
      middleSuffix: s.mid ?? "",
      currentVesting: s.vesting ?? "",
      deedType: s.deedType ?? "",
      phone: s.phone ?? "",
      email: s.email ?? "",
      mailingAddress: s.addr ?? "",
      recordedDocNo: s.docNo ?? "",
      ssnTaxId: s.ssn ?? "",
    })),
    escrowTitles: [{
      titleOffice: escrow.titleOffice ?? parties?.titleOffice ?? "",
      titleBranch: escrow.branch ?? parties?.branch ?? "",
      titleOfficer: parties?.titleOfficer ?? "",
      titleOfficerEmail: parties?.titleOfficerEmail ?? "",
      escrowOffice: escrow.escrowOffice ?? parties?.escrowOffice ?? "",
      escrowOfficer: parties?.escrowOfficer ?? "",
      escrowOfficerEmail: parties?.escrowOfficerEmail ?? "",
      loanOfficer: escrow.loanOfficer ?? parties?.loanOfficer ?? "",
      lenderBank: escrow.lender ?? parties?.lender ?? "",
    }],
    listingAgents: parties?.laCompany ? [{
      companyName: parties.laCompany ?? "",
      companyDre: parties.laCompDre ?? "",
      contactName: parties.laContact ?? "",
      contactDre: parties.laContDre ?? "",
      address: parties.laAddr ?? "",
      city: parties.laCity ?? "",
      state: parties.laState ?? "",
      zip: parties.laZip ?? "",
      phone: parties.laPhone ?? "",
      fax: parties.laFax ?? "",
      mobile: parties.laMobile ?? "",
      email: parties.laEmail ?? "",
      refNo: parties.laRef ?? "",
    }] : [],
    sellingAgents: parties?.saCompany ? [{
      companyName: parties.saCompany ?? "",
      companyDre: parties.saCompDre ?? "",
      contactName: parties.saContact ?? "",
      contactDre: parties.saContDre ?? "",
      address: parties.saAddr ?? "",
      city: parties.saCity ?? "",
      state: parties.saState ?? "",
      zip: parties.saZip ?? "",
      phone: parties.saPhone ?? "",
      fax: parties.saFax ?? "",
      mobile: parties.saMobile ?? "",
      email: parties.saEmail ?? "",
      refNo: parties.saRef ?? "",
    }] : [],
    listingSellingAgents: parties?.lsaCompany ? [{
      companyName: parties.lsaCompany ?? "",
      companyDre: parties.lsaCompDre ?? "",
      contactName: parties.lsaContact ?? "",
      contactDre: parties.lsaContDre ?? "",
      address: parties.lsaAddr ?? "",
      city: parties.lsaCity ?? "",
      state: parties.lsaState ?? "",
      zip: parties.lsaZip ?? "",
      phone: parties.lsaPhone ?? "",
      fax: parties.lsaFax ?? "",
      mobile: parties.lsaMobile ?? "",
      email: parties.lsaEmail ?? "",
      refNo: parties.lsaRef ?? "",
    }] : [],
    lenders: parties?.ldCompany ? [{
      companyName: parties.ldCompany ?? "",
      companyNmls: parties.ldCompNmls ?? "",
      contactName: parties.ldContact ?? "",
      contactNmls: parties.ldContNmls ?? "",
      address: parties.ldAddr ?? "",
      city: parties.ldCity ?? "",
      state: parties.ldState ?? "",
      zip: parties.ldZip ?? "",
      phone: parties.ldPhone ?? "",
      fax: parties.ldFax ?? "",
      mobile: parties.ldMobile ?? "",
      email: parties.ldEmail ?? "",
      refNo: parties.ldRef ?? "",
    }] : [],
    mortgageBrokers: parties?.mbCompany ? [{
      companyName: parties.mbCompany ?? "",
      companyNmls: parties.mbCompNmls ?? "",
      contactName: parties.mbContact ?? "",
      contactNmls: parties.mbContNmls ?? "",
      address: parties.mbAddr ?? "",
      city: parties.mbCity ?? "",
      state: parties.mbState ?? "",
      zip: parties.mbZip ?? "",
      phone: parties.mbPhone ?? "",
      fax: parties.mbFax ?? "",
      mobile: parties.mbMobile ?? "",
      email: parties.mbEmail ?? "",
      refNo: parties.mbRef ?? "",
    }] : [],
    primaryContacts: parties?.pcCompany ? [{
      companyName: parties.pcCompany ?? "",
      companyId: parties.pcCompId ?? "",
      contactName: parties.pcContact ?? "",
      contactId: parties.pcContId ?? "",
      address: parties.pcAddr1 ?? "",
      city: parties.pcCity ?? "",
      state: parties.pcState ?? "",
      zip: parties.pcZip ?? "",
      phone: parties.pcPhone ?? "",
      email: parties.pcEmail ?? "",
    }] : [],
    clients: parties?.clCompany ? [{
      companyName: parties.clCompany ?? "",
      companyId: parties.clCompId ?? "",
      contactName: parties.clContact ?? "",
      contactId: parties.clContId ?? "",
      address: parties.clAddr ?? "",
      city: parties.clCity ?? "",
      state: parties.clState ?? "",
      zip: parties.clZip ?? "",
      phone: parties.clPhone ?? "",
      email: parties.clEmail ?? "",
    }] : [],
  }
}
